name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        otp: ["26.x", "27.x"]
        elixir: ["1.17", "1.18"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.variation.otp}}
          elixir-version: ${{matrix.variation.elixir}}

      - name: Fetch dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
